name: Build release

on:
  release:
    types:
      - published

jobs:
  version:
    name: Extract version from git tag
    runs-on: ubuntu-latest
    steps:
      - id: version
        run: echo "version=$(echo $GITHUB_REF | sed 's/refs\/tags\///')" | tee -a $GITHUB_OUTPUT
    outputs:
      version: ${{ steps.version.outputs.version }}
  build:
    name: Build plugin jar
    runs-on: ubuntu-latest
    needs: version
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
      - run: mvn versions:set -DnewVersion=${{ needs.version.outputs.version }} -DgenerateBackupPoms=false
      - run: mvn clean package -P spigot
      - run: mvn clean package -P paper
      - uses: actions/upload-artifact@v4
        with:
          name: build
          path: bluemapmobs/target/bluemapmobs-*.jar
  upload_release:
    name: Upload jar to release
    runs-on: ubuntu-latest
    needs:
      - build
    permissions:
      contents: write
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: build
          path: .
      - uses: svenstaro/upload-release-action@v2
        with:
          file: bluemapmobs-*.jar
          file_glob: true